BATCH_SIZE=0.9
INDIVIDUAL_LEN=0 # Será definido pelo número de atributos
BINARY_REPRESENTATION_SIZE=8
WEIGHT_THRESHOLD = 0.6
NUM_ATTR = 0 # Será definido pelo dataset

GENERATIONS=100
MUTATION_RATE=0.015
POPULATION_SIZE=100